---
version: "2"
services:
#SAMBA
  samba:
    image: dperson/samba:rpi
    restart: always
    command: -u "andres;pi" -s "media;/media;yes;no"
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - /home/andres/media:/media
#OCTOPRINT
  octoprint1:
    container_name: Octoprint1
    image: octoprint/octoprint
    hostname: Octoprint1
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:8080
    volumes:
      - /home/andres/octoprint1:/octoprint1
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -d /dev/video0:/dev/video0 -r 1280x720 -f 30
    devices:
      #Printer Port
      - /dev/ttyUSB0:/dev/ttyUSB0
     #Webcam port
      - /dev/video0:/dev/video0
